# Generated by Django 5.0 on 2025-08-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_productgallery_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gtin',
            field=models.CharField(blank=True, help_text='Global Trade Item Number (13-14 digits)', max_length=14, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer_part_number',
            field=models.CharField(blank=True, help_text="Manufacturer's part number (custom product ID)", max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='upc_ean',
            field=models.CharField(blank=True, help_text='UPC (12 digits) or EAN (13 digits)', max_length=13, null=True, unique=True),
        ),
    ]
