# Generated by Django 5.0 on 2025-08-27 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_gtin_product_manufacturer_part_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'ordering': ['order'], 'verbose_name': 'product gallery', 'verbose_name_plural': 'product gallery'},
        ),
        migrations.AddField(
            model_name='productgallery',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
