# Generated by Django 5.0 on 2025-08-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_productgallery_options_productgallery_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_variants',
            field=models.BooleanField(default=False, help_text='Enable if this product has variants (e.g., Gas Type).'),
        ),
    ]
