# Generated by Django 5.0 on 2025-08-29 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='warranty_file',
            field=models.FileField(blank=True, help_text='Upload warranty document (e.g., PDF)', null=True, upload_to='warranties/'),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_text',
            field=models.TextField(blank=True, help_text='Warranty description text', null=True),
        ),
        migrations.CreateModel(
            name='ProductDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Download', help_text="Title for the file (e.g., 'Product Catalog')", max_length=100)),
                ('file', models.FileField(help_text='Upload PDF or catalog file', upload_to='downloads/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='store.product')),
            ],
        ),
    ]
