# Generated by Django 5.0 on 2025-09-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_wishlist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='variations',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
    ]
