# Generated by Django 5.0 on 2025-09-03 21:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_wishlist_unique_together_wishlist_variations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='variation',
            index=models.Index(fields=['variation_category'], name='store_varia_variati_3bf4ce_idx'),
        ),
        migrations.AddIndex(
            model_name='variation',
            index=models.Index(fields=['variation_value'], name='store_varia_variati_c3676b_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['user', 'product'], name='store_wishl_user_id_885a73_idx'),
        ),
    ]
