# Generated by Django 5.0 on 2025-09-11 18:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_wishlist_quantity'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='variation',
            name='store_varia_variati_3bf4ce_idx',
        ),
        migrations.RemoveIndex(
            model_name='variation',
            name='store_varia_variati_c3676b_idx',
        ),
        migrations.AddField(
            model_name='variation',
            name='display_type',
            field=models.CharField(choices=[('dropdown', 'Dropdown'), ('button', 'Button'), ('radio', 'Radio')], default='dropdown', help_text='How should this option appear on the product page?', max_length=20),
        ),
        migrations.AddField(
            model_name='variation',
            name='price_adjustment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Extra price (can be positive or negative).', max_digits=10),
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(max_length=100),
        ),
    ]
