# Generated by Django 5.0 on 2025-09-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_variationcategory_remove_variation_display_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight_lbs',
            field=models.PositiveIntegerField(default=1, help_text='Weight of this product in whole pounds (auto-rounded up).'),
        ),
    ]
