# Generated by Django 5.0 on 2025-09-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_product_weight_lbs'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='height_in',
            field=models.PositiveIntegerField(default=6, help_text='Package height in inches (whole numbers only).'),
        ),
        migrations.AddField(
            model_name='product',
            name='length_in',
            field=models.PositiveIntegerField(default=7, help_text='Package length in inches (whole numbers only).'),
        ),
        migrations.AddField(
            model_name='product',
            name='width_in',
            field=models.PositiveIntegerField(default=6, help_text='Package width in inches (whole numbers only).'),
        ),
    ]
