# Generated by Django 5.0 on 2025-08-26 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_blockedip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlockedIP',
        ),
    ]
