# Generated by Django 5.0 on 2025-08-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_delete_blockedip'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
                ('is_blocked', models.BooleanField(default=True)),
            ],
        ),
    ]
