# Generated by Django 5.0 on 2025-09-04 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_blockedip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlockedIP',
        ),
    ]
