# Generated by Django 5.0 on 2025-10-06 18:00

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPalWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_shipping_enabled', models.BooleanField(default=True, help_text='Enable free shipping for qualifying orders.')),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=Decimal('99.00'), help_text='Minimum subtotal for free shipping.', max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50)),
                ('address_line_1', models.CharField(max_length=50)),
                ('address_line_2', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(default='US', max_length=2)),
                ('state', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('order_note', models.CharField(blank=True, max_length=100)),
                ('order_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, help_text='Final shipping cost applied to this order', max_digits=10)),
                ('status', models.CharField(choices=[('AUTHORIZED', 'Authorized'), ('PENDING', 'Pending'), ('CAPTURED', 'Captured'), ('REFUNDED', 'Refunded')], default='AUTHORIZED', max_length=10, verbose_name='Payment Status')),
                ('tracking_number', models.CharField(blank=True, help_text='Carrier tracking number for shipment', max_length=100, null=True)),
                ('order_status', models.CharField(choices=[('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('CANCELLED', 'Cancelled'), ('RETURNED', 'Returned')], default='PROCESSING', max_length=15)),
                ('is_ordered', models.BooleanField(default=False)),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipping_first_name', models.CharField(blank=True, max_length=50)),
                ('shipping_last_name', models.CharField(blank=True, max_length=50)),
                ('shipping_phone', models.CharField(blank=True, max_length=15)),
                ('shipping_email', models.EmailField(blank=True, max_length=50)),
                ('shipping_address_line_1', models.CharField(blank=True, max_length=50)),
                ('shipping_address_line_2', models.CharField(blank=True, max_length=50)),
                ('shipping_country', models.CharField(blank=True, default='US', max_length=2)),
                ('shipping_state', models.CharField(blank=True, max_length=2)),
                ('shipping_city', models.CharField(blank=True, max_length=50)),
                ('shipping_zip_code', models.CharField(blank=True, max_length=20)),
                ('shipping_method', models.CharField(blank=True, help_text='Carrier or type (e.g., FedEx Home, Free Shipping)', max_length=50, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=255, null=True)),
                ('po_number', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier_order_date', models.DateField(blank=True, null=True)),
                ('paypal_authorization_id', models.CharField(blank=True, max_length=255, null=True)),
                ('paypal_order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100)),
                ('payment_method', models.CharField(max_length=100)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product_price', models.FloatField()),
                ('ordered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('variations', models.ManyToManyField(blank=True, to='store.variation')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.payment')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.payment'),
        ),
    ]
