# Generated by Django 5.0 on 2025-10-06 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='custom_carrier_details',
            field=models.CharField(blank=True, help_text='Additional details for custom carriers (e.g., Freight company name and tracking URL)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_carrier',
            field=models.CharField(blank=True, choices=[('FedEx', 'FedEx'), ('UPS', 'UPS'), ('USPS', 'USPS'), ('Freight', 'Freight'), ('Other', 'Other')], help_text='Shipping carrier', max_length=50, null=True),
        ),
    ]
