# Generated by Django 5.0 on 2025-09-22 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('CANCELLED', 'Cancelled'), ('RETURNED', 'Returned')], default='PROCESSING', max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('AUTHORIZED', 'Authorized'), ('PENDING', 'Pending'), ('CAPTURED', 'Captured'), ('REFUNDED', 'Refunded')], default='AUTHORIZED', max_length=10, verbose_name='Payment Status'),
        ),
    ]
