# Generated by Django 5.0 on 2025-09-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_order_total_alter_order_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, help_text='Carrier tracking number for shipment', max_length=100, null=True),
        ),
    ]
