# Generated by Django 5.0 on 2025-10-03 20:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_paypal_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_shipping_enabled', models.BooleanField(default=True, help_text='Enable free shipping for qualifying orders.')),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=Decimal('99.00'), help_text='Minimum subtotal for free shipping.', max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
